"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 1845.6904
   ACS = 3087.5176
   TRA = 0.0
   TRW = 0.0
   TOT = 4933.208
   ..
"Electricidad Demanda" = INFORME
   ENERGIA = Electricidad
   TIPO = Demanda
   REF = 446.61615
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 446.61615
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 446.61615
   CAL = 1845.6904
   ACS = 3087.5176
   TRA = 0.0
   TRW = 0.0
   TOT = 5379.824
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 2947.513
   ACS = 3859.4907
   TRA = 0.0
   TRW = 0.0
   TOT = 6807.004
   ..
"Electricidad Energía Final" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Final
   REF = 169.51634
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 169.51634
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 169.51634
   CAL = 2947.513
   ACS = 3859.4907
   TRA = 0.0
   TRW = 0.0
   TOT = 6976.5205
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 250.5386
   ACS = 328.05673
   TRA = 0.0
   TRW = 0.0
   TOT = 578.59534
   ..
"Electricidad Energía Primaria" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Primaria
   REF = 331.23492
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 331.23492
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 331.23492
   CAL = 250.5386
   ACS = 328.05673
   TRA = 0.0
   TRW = 0.0
   TOT = 909.83026
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 53.05523
   ACS = 69.470825
   TRA = 0.0
   TRW = 0.0
   TOT = 122.52606
   ..
"Electricidad Emisiones CO2" = INFORME
   ENERGIA = Electricidad
   TIPO = Emisiones CO2
   REF = 56.109913
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 56.109913
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 56.109913
   CAL = 53.05523
   ACS = 69.470825
   TRA = 0.0
   TRW = 0.0
   TOT = 178.63597
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (0,0,0,0,0,0,0,0,0,0,0,0)
   NHFALTOREFRI = (0,0,0,0,0,1,2,0,3,0,0,0)
   NHFALTOCLIMA = (0,0,0,0,0,1,2,0,3,0,0,0)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,4.170811,1.6229626,0.0,3.363197,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
