"Gasoleo calefaccion / Fuel-oil Demanda" = INFORME
   ENERGIA = Gasoleo calefaccion / Fuel-oil
   TIPO = Demanda
   REF = 0.0
   CAL = 88416.234
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 88416.234
   ..
"Electricidad Demanda" = INFORME
   ENERGIA = Electricidad
   TIPO = Demanda
   REF = 55171.527
   CAL = 0.0
   ACS = 5997.208
   TRA = 0.0
   TRW = 0.0
   TOT = 61168.734
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 55171.527
   CAL = 88416.234
   ACS = 5997.208
   TRA = 0.0
   TRW = 0.0
   TOT = 149584.95
   ..
"Gasoleo calefaccion / Fuel-oil Energía Final" = INFORME
   ENERGIA = Gasoleo calefaccion / Fuel-oil
   TIPO = Energía Final
   REF = 0.0
   CAL = 126308.9
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 126308.9
   ..
"Electricidad Energía Final" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Final
   REF = 32453.844
   CAL = 0.0
   ACS = 5997.208
   TRA = 0.0
   TRW = 0.0
   TOT = 38451.05
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 32453.844
   CAL = 126308.9
   ACS = 5997.208
   TRA = 0.0
   TRW = 0.0
   TOT = 164759.95
   ..
"Gasoleo calefaccion / Fuel-oil Energía Primaria" = INFORME
   ENERGIA = Gasoleo calefaccion / Fuel-oil
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 148918.19
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 148918.19
   ..
"Electricidad Energía Primaria" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Primaria
   REF = 63414.816
   CAL = 0.0
   ACS = 11718.544
   TRA = 0.0
   TRW = 0.0
   TOT = 75133.36
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 63414.816
   CAL = 148918.19
   ACS = 11718.544
   TRA = 0.0
   TRW = 0.0
   TOT = 224051.55
   ..
"Gasoleo calefaccion / Fuel-oil Emisiones CO2" = INFORME
   ENERGIA = Gasoleo calefaccion / Fuel-oil
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 39282.066
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 39282.066
   ..
"Electricidad Emisiones CO2" = INFORME
   ENERGIA = Electricidad
   TIPO = Emisiones CO2
   REF = 10742.224
   CAL = 0.0
   ACS = 1985.0759
   TRA = 0.0
   TRW = 0.0
   TOT = 12727.3
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 10742.224
   CAL = 39282.066
   ACS = 1985.0759
   TRA = 0.0
   TRW = 0.0
   TOT = 52009.367
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (248,224,248,240,248,240,248,248,240,248,240,248)
   NHFUNREFRI = (248,224,248,240,248,240,248,248,240,248,240,248)
   NHFUNCLIMA= (248,224,248,240,248,240,248,248,240,248,240,248)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (0,0,0,0,0,0,0,0,0,0,0,0)
   NHFALTOREFRI = (0,0,0,0,0,0,0,0,0,0,0,0)
   NHFALTOCLIMA = (0,0,0,0,0,0,0,0,0,0,0,0)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
