"Biomasa no densificada Demanda" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Demanda
   REF = 0.0
   CAL = 4813.692
   ACS = 1227.0992
   TRA = 0.0
   TRW = 0.0
   TOT = 6040.791
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 4813.692
   ACS = 1227.0992
   TRA = 0.0
   TRW = 0.0
   TOT = 6040.791
   ..
"Biomasa no densificada Energía Final" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Final
   REF = 0.0
   CAL = 7011.0913
   ACS = 1319.4625
   TRA = 0.0
   TRW = 0.0
   TOT = 8330.554
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 7011.0913
   ACS = 1319.4625
   TRA = 0.0
   TRW = 0.0
   TOT = 8330.554
   ..
"Biomasa no densificada Energía Primaria" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 238.37712
   ACS = 44.861725
   TRA = 0.0
   TRW = 0.0
   TOT = 283.23883
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 238.37712
   ACS = 44.861725
   TRA = 0.0
   TRW = 0.0
   TOT = 283.23883
   ..
"Biomasa no densificada Emisiones CO2" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 126.19964
   ACS = 23.750324
   TRA = 0.0
   TRW = 0.0
   TOT = 149.94997
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 126.19964
   ACS = 23.750324
   TRA = 0.0
   TRW = 0.0
   TOT = 149.94997
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (27,24,17,10,1,0,0,0,0,0,14,28)
   NHFALTOREFRI = (0,0,0,0,0,0,51,39,20,0,0,0)
   NHFALTOCLIMA = (27,24,17,10,1,0,51,39,20,0,14,28)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (21.413294,17.329025,11.950576,4.4533415,0.4533335,0.0,0.0,0.0,0.0,0.0,8.033751,20.860159)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,0.0,30.919722,24.417376,10.404777,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
