"Biomasa no densificada Demanda" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Demanda
   REF = 0.0
   CAL = 2879.9163
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 3971.947
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 2879.9163
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 3971.947
   ..
"Biomasa no densificada Energía Final" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Final
   REF = 0.0
   CAL = 4193.106
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5367.333
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 4193.106
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5367.333
   ..
"Biomasa no densificada Energía Primaria" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 142.56561
   ACS = 39.92372
   TRA = 0.0
   TRW = 0.0
   TOT = 182.48933
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 142.56561
   ACS = 39.92372
   TRA = 0.0
   TRW = 0.0
   TOT = 182.48933
   ..
"Biomasa no densificada Emisiones CO2" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 75.4759
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 96.611984
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 75.4759
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 96.611984
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (23,16,11,1,0,0,0,0,0,0,5,16)
   NHFALTOREFRI = (0,0,0,0,0,112,286,289,178,0,0,0)
   NHFALTOCLIMA = (23,16,11,1,0,112,286,289,178,0,5,16)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (12.856877,9.622193,6.292536,0.36876854,0.0,0.0,0.0,0.0,0.0,0.0,2.5895596,10.052719)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,90.42042,241.18973,232.71745,122.05015,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
