"Gas Natural Demanda" = INFORME
   ENERGIA = Gas Natural
   TIPO = Demanda
   REF = 0.0
   CAL = 17214.416
   ACS = 13970.626
   TRA = 0.0
   TRW = 0.0
   TOT = 31185.043
   ..
"Electricidad Demanda" = INFORME
   ENERGIA = Electricidad
   TIPO = Demanda
   REF = 11704.041
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 11704.041
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 11704.041
   CAL = 17214.416
   ACS = 13970.626
   TRA = 0.0
   TRW = 0.0
   TOT = 42889.086
   ..
"Gas Natural Energía Final" = INFORME
   ENERGIA = Gas Natural
   TIPO = Energía Final
   REF = 0.0
   CAL = 17081.652
   ACS = 15575.279
   TRA = 0.0
   TRW = 0.0
   TOT = 32656.932
   ..
"Electricidad Energía Final" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Final
   REF = 3593.7312
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 3593.7312
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 3593.7312
   CAL = 17081.652
   ACS = 15575.279
   TRA = 0.0
   TRW = 0.0
   TOT = 36250.664
   ..
"Gas Natural Energía Primaria" = INFORME
   ENERGIA = Gas Natural
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 20327.166
   ACS = 18534.582
   TRA = 0.0
   TRW = 0.0
   TOT = 38861.746
   ..
"Electricidad Energía Primaria" = INFORME
   ENERGIA = Electricidad
   TIPO = Energía Primaria
   REF = 7022.151
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 7022.151
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 7022.151
   CAL = 20327.166
   ACS = 18534.582
   TRA = 0.0
   TRW = 0.0
   TOT = 45883.9
   ..
"Gas Natural Emisiones CO2" = INFORME
   ENERGIA = Gas Natural
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 4304.5767
   ACS = 3924.9702
   TRA = 0.0
   TRW = 0.0
   TOT = 8229.547
   ..
"Electricidad Emisiones CO2" = INFORME
   ENERGIA = Electricidad
   TIPO = Emisiones CO2
   REF = 1189.525
   CAL = 0.0
   ACS = 0.0
   TRA = 0.0
   TRW = 0.0
   TOT = 1189.525
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 1189.525
   CAL = 4304.5767
   ACS = 3924.9702
   TRA = 0.0
   TRW = 0.0
   TOT = 9419.072
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (680,671,633,261,137,0,0,0,0,12,505,744)
   NHFALTOREFRI = (0,0,0,0,0,95,197,262,132,0,0,0)
   NHFALTOCLIMA = (680,671,633,261,137,95,197,262,132,12,505,744)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (852.9714,483.7526,283.2041,41.105213,17.898663,0.0,0.0,0.0,0.0,4.266046,265.8667,818.2377)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,78.68404,260.14908,333.04755,144.83795,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
