"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 4460.275
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 7277.864
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 4460.275
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 7277.864
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 6356.2266
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 9385.895
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 6356.2266
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 9385.895
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 540.27924
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 797.80115
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 540.27924
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 797.80115
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 114.41207
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 168.9461
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 114.41207
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 168.9461
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (27,20,13,0,0,0,0,0,0,0,10,25)
   NHFALTOREFRI = (0,0,0,0,0,110,264,257,135,0,0,0)
   NHFALTOCLIMA = (27,20,13,0,0,110,264,257,135,0,10,25)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (29.545029,19.680723,12.613397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.4246745,27.56519)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,89.63715,292.71658,278.20428,124.67842,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
