"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 4268.373
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 7085.962
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 4268.373
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 7085.962
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 6084.54
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 9114.209
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 6084.54
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 9114.209
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 517.1859
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 774.70776
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 517.1859
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 774.70776
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 109.52172
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 164.05576
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 109.52172
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 164.05576
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (27,18,13,0,0,0,0,0,0,0,7,23)
   NHFALTOREFRI = (0,0,0,0,0,122,274,281,157,0,0,0)
   NHFALTOCLIMA = (27,18,13,0,0,122,274,281,157,0,7,23)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (27.917313,17.432966,11.52818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.7157598,24.998415)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,102.70556,309.6451,298.8401,136.0054,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
