"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 2928.7158
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 4020.7466
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 2928.7158
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 4020.7466
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 4263.7246
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5437.9517
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 4263.7246
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5437.9517
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 362.4166
   ACS = 99.8093
   TRA = 0.0
   TRW = 0.0
   TOT = 462.2259
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 362.4166
   ACS = 99.8093
   TRA = 0.0
   TRW = 0.0
   TOT = 462.2259
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 76.74704
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 97.883125
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 76.74704
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 97.883125
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (23,16,11,1,0,0,0,0,0,0,5,16)
   NHFALTOREFRI = (0,0,0,0,0,29,123,144,77,0,0,0)
   NHFALTOCLIMA = (23,16,11,1,0,29,123,144,77,0,5,16)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (12.966916,9.843066,6.3749843,0.37035352,0.0,0.0,0.0,0.0,0.0,0.0,2.5872788,10.178867)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,16.347504,108.17558,99.29299,46.547543,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
