"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 3731.9646
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 6549.554
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 3731.9646
   ACS = 2817.5894
   TRA = 0.0
   TRW = 0.0
   TOT = 6549.554
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 5325.528
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 8355.197
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 5325.528
   ACS = 3029.6687
   TRA = 0.0
   TRW = 0.0
   TOT = 8355.197
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 452.66986
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 710.1918
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 452.66986
   ACS = 257.52185
   TRA = 0.0
   TRW = 0.0
   TOT = 710.1918
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 95.8595
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 150.39352
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 95.8595
   ACS = 54.534035
   TRA = 0.0
   TRW = 0.0
   TOT = 150.39352
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (27,19,13,0,0,0,0,0,0,0,8,25)
   NHFALTOREFRI = (0,0,0,0,0,120,268,269,148,0,0,0)
   NHFALTOCLIMA = (27,19,13,0,0,120,268,269,148,0,8,25)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (27.599157,17.9433,12.225169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.472915,24.568136)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,101.10552,292.98358,280.7446,126.01903,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
