"Biomasa no densificada Demanda" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Demanda
   REF = 0.0
   CAL = 2898.1096
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 3990.1401
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 2898.1096
   ACS = 1092.0308
   TRA = 0.0
   TRW = 0.0
   TOT = 3990.1401
   ..
"Biomasa no densificada Energía Final" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Final
   REF = 0.0
   CAL = 4219.042
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5393.269
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 4219.042
   ACS = 1174.2272
   TRA = 0.0
   TRW = 0.0
   TOT = 5393.269
   ..
"Biomasa no densificada Energía Primaria" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 143.44743
   ACS = 39.92372
   TRA = 0.0
   TRW = 0.0
   TOT = 183.37115
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 143.44743
   ACS = 39.92372
   TRA = 0.0
   TRW = 0.0
   TOT = 183.37115
   ..
"Biomasa no densificada Emisiones CO2" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 75.94275
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 97.078835
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 75.94275
   ACS = 21.136087
   TRA = 0.0
   TRW = 0.0
   TOT = 97.078835
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (23,16,11,1,0,0,0,0,0,0,5,16)
   NHFALTOREFRI = (0,0,0,0,0,28,122,139,75,0,0,0)
   NHFALTOCLIMA = (23,16,11,1,0,28,122,139,75,0,5,16)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (12.856877,9.622193,6.292536,0.36876854,0.0,0.0,0.0,0.0,0.0,0.0,2.591481,10.053508)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,16.288132,106.70161,96.26175,45.069767,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
