"Biomasa densificada (pelets) Demanda" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Demanda
   REF = 0.0
   CAL = 2933.7712
   ACS = 1136.6309
   TRA = 0.0
   TRW = 0.0
   TOT = 4070.402
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 2933.7712
   ACS = 1136.6309
   TRA = 0.0
   TRW = 0.0
   TOT = 4070.402
   ..
"Biomasa densificada (pelets) Energía Final" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Final
   REF = 0.0
   CAL = 4270.3384
   ACS = 1222.183
   TRA = 0.0
   TRW = 0.0
   TOT = 5492.5215
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 4270.3384
   ACS = 1222.183
   TRA = 0.0
   TRW = 0.0
   TOT = 5492.5215
   ..
"Biomasa densificada (pelets) Energía Primaria" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 362.9788
   ACS = 103.88555
   TRA = 0.0
   TRW = 0.0
   TOT = 466.86435
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 362.9788
   ACS = 103.88555
   TRA = 0.0
   TRW = 0.0
   TOT = 466.86435
   ..
"Biomasa densificada (pelets) Emisiones CO2" = INFORME
   ENERGIA = Biomasa densificada (pelets)
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 76.86609
   ACS = 21.999292
   TRA = 0.0
   TRW = 0.0
   TOT = 98.86537
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 76.86609
   ACS = 21.999292
   TRA = 0.0
   TRW = 0.0
   TOT = 98.86537
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (23,16,11,1,0,0,0,0,0,0,5,16)
   NHFALTOREFRI = (0,0,0,0,0,29,123,144,77,0,0,0)
   NHFALTOCLIMA = (23,16,11,1,0,29,123,144,77,0,5,16)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (13.008164,9.8726425,6.394357,0.37222314,0.0,0.0,0.0,0.0,0.0,0.0,2.5962446,10.207709)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,16.355625,108.22373,99.33032,46.563385,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
