[book]
title = "Ejemplo I Config 2"
authors = ["Tomas Gonzalez Llarena <alu0101841946@ull.edu.es>"]

[output.pandoc.profile.pdf]
output-file = "Ejemplo_I_Config_2.pdf"
pdf-engine = "lualatex"
filters = ["mermaid-filter.cmd","pandoc-plantuml.cmd"]
keep-tex = true

[output.pandoc.profile.pdf.variables]
mainfont = "DejaVu Sans"
monofont = "DejaVu Sans Mono"
geometry = "margin=1.5cm"
documentclass = "article"
classoption = ["10pt"]
header-includes = "\\usepackage{svg}"
mermaid-format = "svg"
mermaid-theme = "default"
mermaid-width = "600"
mermaid-scale = "2"