"Biomasa no densificada Demanda" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Demanda
   REF = 0.0
   CAL = 3114.7375
   ACS = 1287.814
   TRA = 0.0
   TRW = 0.0
   TOT = 4402.5513
   ..
"Global Demanda" = INFORME
   ENERGIA = TODAS
   TIPO = Demanda
   REF = 0.0
   CAL = 3114.7375
   ACS = 1287.814
   TRA = 0.0
   TRW = 0.0
   TOT = 4402.5513
   ..
"Biomasa no densificada Energía Final" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Final
   REF = 0.0
   CAL = 4535.026
   ACS = 1384.7466
   TRA = 0.0
   TRW = 0.0
   TOT = 5919.7725
   ..
"Global Energía Final" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Final
   REF = 0.0
   CAL = 4535.026
   ACS = 1384.7466
   TRA = 0.0
   TRW = 0.0
   TOT = 5919.7725
   ..
"Biomasa no densificada Energía Primaria" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 154.19089
   ACS = 47.081387
   TRA = 0.0
   TRW = 0.0
   TOT = 201.27228
   ..
"Global Energía Primaria" = INFORME
   ENERGIA = TODAS
   TIPO = Energía Primaria
   REF = 0.0
   CAL = 154.19089
   ACS = 47.081387
   TRA = 0.0
   TRW = 0.0
   TOT = 201.27228
   ..
"Biomasa no densificada Emisiones CO2" = INFORME
   ENERGIA = Biomasa no densificada
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 81.63046
   ACS = 24.925438
   TRA = 0.0
   TRW = 0.0
   TOT = 106.5559
   ..
"Global Emisiones CO2" = INFORME
   ENERGIA = TODAS
   TIPO = Emisiones CO2
   REF = 0.0
   CAL = 81.63046
   ACS = 24.925438
   TRA = 0.0
   TRW = 0.0
   TOT = 106.5559
   ..
"Disconfort" = INFORME
   NHFUNCALEF = (744,672,744,720,744,0,0,0,0,744,720,744)
   NHFUNREFRI = (0,0,0,0,0,480,496,496,480,0,0,0)
   NHFUNCLIMA= (744,672,744,720,744,480,496,496,480,744,720,744)
   NHFUNACS= (620,560,620,600,620,600,620,620,600,620,600,620)
   NHFALTOCALEF = (23,16,11,2,0,0,0,0,0,0,6,16)
   NHFALTOREFRI = (0,0,0,0,0,17,108,114,63,0,0,0)
   NHFALTOCLIMA = (23,16,11,2,0,17,108,114,63,0,6,16)
   NHFALTOACS = (0,0,0,0,0,0,0,0,0,0,0,0)
   QNOCUBIERTACALEF = (13.246665,10.038893,6.557368,0.7974453,0.0,0.0,0.0,0.0,0.0,0.0,3.082543,10.314125)
   QNOCUBIERTAREFRI = (0.0,0.0,0.0,0.0,0.0,9.902545,89.756065,76.28502,34.55752,0.0,0.0,0.0)
   QNOCUBIERTAACS = (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
   ..
